const dict: Record<string, string> = {
  // Navigation
  "nav.back": "返回首页",
  "nav.backTo": "返回",
  "nav.home": "首页",

  // Auth
  "auth.login": "登录",
  "auth.register": "注册",
  "auth.logout": "退出登录",
  "auth.email": "邮箱",
  "auth.password": "密码",
  "auth.confirm_password": "确认密码",
  "auth.name": "姓名",
  "auth.name_optional": "姓名（选填）",
  "auth.forgot_password": "忘记密码？",
  "auth.contact_admin": "请联系超级管理员重置密码",
  "auth.no_account": "还没有账号？",
  "auth.have_account": "已有账号？",
  "auth.login_now": "立即登录",
  "auth.register_now": "立即注册",
  "auth.create_account": "创建账号",
  "auth.login_success": "登录成功",
  "auth.register_success": "注册成功",
  "auth.register_pending": "注册成功！请等待超级管理员审批后登录",
  "auth.i_am": "我是...",
  "auth.student": "学生",
  "auth.student_desc": "申请项目",
  "auth.staff": "工作人员",
  "auth.staff_desc": "需审批",
  "auth.staff_notice": "工作人员账号需要超级管理员审批后才能登录",
  "auth.password_min": "密码至少需要6个字符",
  "auth.passwords_not_match": "两次密码输入不一致",
  "auth.email_invalid": "邮箱格式不正确",
  "auth.email_exists": "该邮箱已被注册",
  "auth.email_password_wrong": "邮箱或密码错误",
  "auth.pending_approval": "您的账号正在等待审批，请联系超级管理员",
  "auth.rejected": "您的账号已被拒绝，请联系超级管理员",
  "auth.suspended": "您的账号已被停用，请联系超级管理员",
  "auth.login_failed": "登录失败，请重试",
  "auth.register_failed": "注册失败，请重试",
  "auth.at_least_6_chars": "至少6个字符",
  "auth.creating_account": "创建账号中...",
  "auth.logging_in": "登录中...",
  "auth.back_home": "返回首页",

  // User Management (Admin)
  "admin.users.title": "用户管理",
  "admin.users.subtitle": "管理学生和工作人员账号",
  "admin.users.students": "学生",
  "admin.users.staff": "工作人员",
  "admin.users.pending": "待审批",
  "admin.users.total": "总用户数",
  "admin.users.all": "全部用户",
  "admin.users.pending_only": "待审批",
  "admin.users.search_placeholder": "搜索邮箱或姓名...",
  "admin.users.user": "用户",
  "admin.users.role": "角色",
  "admin.users.status": "状态",
  "admin.users.registered": "注册时间",
  "admin.users.actions": "操作",
  "admin.users.manage": "管理",
  "admin.users.no_users": "没有找到用户",
  "admin.users.no_pending": "没有待审批的用户",
  "admin.users.user_details": "用户详情",
  "admin.users.last_login": "最后登录",
  "admin.users.approve": "批准",
  "admin.users.reject": "拒绝",
  "admin.users.suspend": "停用",
  "admin.users.activate": "激活",
  "admin.users.reset_password": "重置密码",
  "admin.users.new_password": "新密码已生成",
  "admin.users.share_password": "请安全地将此密码分享给用户",
  "admin.users.cannot_modify_admin": "无法修改超级管理员账号",
  "admin.users.processing": "处理中...",

  // Staff Dashboard
  "staff.dashboard.title": "工作人员后台",
  "staff.dashboard.welcome": "欢迎，工作人员！",
  "staff.dashboard.desc": "管理项目、审核申请、帮助学生找到最佳匹配",
  "staff.dashboard.programmes": "项目列表",
  "staff.dashboard.programmes_desc": "查看、编辑、添加英国工程项目",
  "staff.dashboard.verify": "数据审核",
  "staff.dashboard.verify_desc": "审核解析数据，确保准确性",
  "staff.dashboard.add_programme": "添加项目",
  "staff.dashboard.add_programme_desc": "手动添加新项目和要求",
  "staff.dashboard.responsibilities": "您的职责",
  "staff.dashboard.resp_1": "维护官方大学网站的项目信息准确性",
  "staff.dashboard.resp_2": "在数据上线前审核AI解析的数据",
  "staff.dashboard.resp_3": "监控学生申请并提供支持",
  "staff.dashboard.resp_4": "根据需要更新时间线事件和截止日期",

  // Homepage
  "home.title": "EngiMatch",
  "home.subtitle": "英国工程硕士项目智能匹配",
  "home.description": "为中国工科本科生精准评估英国院校的适配度",
  "home.ai_resume": "AI 优化简历",
  "home.ai_resume_desc": "检查简历是否适合英国工科硕士申请，逐段给出优化建议",
  "home.create_profile": "创建申请档案",
  "home.create_profile_desc": "录入成绩和背景信息",
  "home.timeline": "申请时间线",
  "home.timeline_desc": "追踪雅思、签证、机票租房等全流程节点",
  "home.admin": "管理后台",
  "home.admin_desc": "管理项目和评估规则",
  "home.login": "登录",
  "home.register": "注册",
  "home.logout": "退出登录",
  "home.go_dashboard": "进入后台",

  // AI Resume
  "ai.title": "AI 优化简历",
  "ai.subtitle": "AI 驱动 · 仅针对英国授课型硕士申请",
  "ai.description": "检查你的简历是否适合英国工科硕士申请，逐段分析问题，给出专业优化建议。",
  "ai.step.usecase": "选择场景",
  "ai.step.upload": "上传简历",
  "ai.step.review": "确认解析",
  "ai.step.diagnose": "查看诊断",
  "ai.step.optimize": "逐段优化",
  "ai.step.final": "最终版本",
  "ai.application_type": "申请类型",
  "ai.uk_master": "英国授课型硕士",
  "ai.uk_master_desc": "MSc / MEng · 主要方向",
  "ai.research_master": "研究型硕士（MRes）",
  "ai.research_master_desc": "暂不支持",
  "ai.major_direction": "学科方向（必选）",
  "ai.current_stage": "当前阶段",
  "ai.stage.no_resume": "还没有简历，想先了解",
  "ai.stage.have_resume": "已有简历，想优化",
  "ai.stage.apply_ready": "准备申请，想检查是否达标",
  "ai.start": "开始上传简历 →",

  // Upload page
  "upload.title": "上传简历",
  "upload.paste_mode": "粘贴简历文本",
  "upload.upload_mode": "上传文件（PDF/Word）",
  "upload.paste_content": "粘贴简历内容",
  "upload.paste_hint": "直接粘贴英文或中英文混排简历均可",
  "upload.paste_clipboard": "粘贴剪贴板",
  "upload.upload_file": "上传简历文件",
  "upload.supported": "支持 PDF、Word (.doc/.docx)、纯文本 (.txt)",
  "upload.select_file": "选择文件",
  "upload.note": "注：PDF/Word 格式需要服务器安装解析库，如提取失败请改用粘贴模式",
  "upload.characters": "已输入 {count} 个字符",
  "upload.too_short": "（内容可能不足）",
  "upload.continue": "解析简历 →",
  "upload.need_more": "还需 {count} 字",
  "upload.extracting": "正在提取文本...",
  "upload.direction": "申请方向：英国授课型硕士",
  "upload.direction_edit": "修改 →",

  // Review page
  "review.title": "简历结构解析结果",
  "review.add_section": "+ 添加段落",
  "review.description": "系统已将你的简历拆分为 {count} 个部分，请确认分类是否正确。",
  "review.hint": "系统提示",
  "review.confirm": "确认并开始诊断 →",
  "review.splitting_method": "分割方式",
  "review.rule_based": "规则分割",
  "review.ai_smart_split": "AI智能分割",
  "review.splitting": "分割中...",
  "review.education_missing": "未识别到教育背景，请手动添加",
  "review.project_missing": "未识别到项目或科研经历，请确认是否已包含",
  "review.skill_missing": "未识别到技能部分，建议补充编程语言和工具",
  "review.parse_failed": "未能解析出内容，请直接粘贴简历文本后重新开始",
  "review.resume_direction": "简历将针对此方向进行评估和优化",

  // Diagnose page
  "diagnose.title": "诊断结果",
  "diagnose.structure": "结构清晰度",
  "diagnose.completeness": "内容完整度",
  "diagnose.target_fit": "申请适配度",
  "diagnose.english_quality": "英文表达质量",
  "diagnose.continue": "开始逐段优化 →",
  "diagnose.diagnosis_complete": "诊断完成",
  "diagnose.diagnosis_desc": "从结构、内容、申请适配度、英文表达四个维度分析你的简历",
  "diagnose.issues_found": "发现问题",
  "diagnose.high_priority": "高优先级",
  "diagnose.med_priority": "中等优先级",
  "diagnose.low_priority": "低优先级",
  "diagnose.structure_good": "简历基础结构良好",
  "diagnose.structure_good_desc": "未检测到明显问题，建议直接进入优化阶段",
  "diagnose.issue_description": "问题描述",
  "diagnose.suggestion": "优化建议",
  "diagnose.deep_analysis": "AI 深度分析中...",
  "diagnose.deep_analysis_desc": "基于你的简历内容给出针对性评价",
  "diagnose.deep_report": "AI 深度分析报告",
  "diagnose.overall_review": "总评",
  "diagnose.ai_unavailable": "AI 诊断暂时不可用",
  "diagnose.modify_parsing": "修改解析",
  "diagnose.start_optimize": "开始优化 →",
  "diagnose.recommendations": "建议补充",

  // Optimize page
  "optimize.title": "优化简历",
  "optimize.select_section": "选择一个段落开始优化",
  "optimize.optimizing": "正在优化...",
  "optimize.original": "原文",
  "optimize.optimized": "优化后",
  "optimize.apply_all": "应用全部优化",
  "optimize.skip": "跳过",

  // Final page
  "final.title": "最终版本",
  "final.download": "下载简历",
  "final.copy": "复制全文",
  "final.copied": "已复制",
  "final.start_over": "重新开始",
  "final.success": "简历优化完成！",

  // Common section types
  "section.education": "教育背景",
  "section.project": "项目经历",
  "section.internship": "实习经历",
  "section.research": "科研经历",
  "section.competition": "竞赛经历",
  "section.skill": "技能与工具",
  "section.award": "获奖情况",
  "section.summary": "个人总结",
  "section.other": "其他",
  "section.new": "新段落",
  "section.title_placeholder": "段落标题",
  "section.content_placeholder": "在此修改内容...",
  "section.personal_info": "个人信息",

  // Applicant page
  "applicant.title": "创建申请档案",
  "applicant.subtitle": "录入你的学术背景，获取英国工程硕士项目匹配结果",
  "applicant.step1": "个人信息",
  "applicant.step2": "学术成绩",
  "applicant.step3": "课程列表",
  "applicant.personal_info": "个人信息",
  "applicant.auto_fill": "粘贴自动填充",
  "applicant.hide_example": "收起示例",
  "applicant.name": "姓名 *",
  "applicant.name_placeholder": "你的真实姓名",
  "applicant.email": "邮箱 *",
  "applicant.email_placeholder": "用于查看结果",
  "applicant.nationality": "国籍",
  "applicant.nationality_placeholder": "如：中国",
  "applicant.university": "本科院校 *",
  "applicant.university_placeholder": "如：同济大学",
  "applicant.major": "本科专业 *",
  "applicant.major_placeholder": "如：机械工程",
  "applicant.graduation_year": "预计毕业年份",
  "applicant.target_direction": "目标申请方向",
  "applicant.target_hint": "可多选，帮助我们筛选最相关的项目",
  "applicant.next_step": "下一步：学术成绩 →",
  "applicant.prev_step": "← 上一步",
  "applicant.gpa": "GPA 成绩 *",
  "applicant.gpa_value": "GPA 数值",
  "applicant.gpa_value_placeholder": "如：3.5",
  "applicant.gpa_scale": "满分制",
  "applicant.gpa_scale_placeholder": "如：4.0",
  "applicant.grading_scheme": "成绩制度",
  "applicant.scheme_4": "4.0制",
  "applicant.scheme_5": "5.0制",
  "applicant.scheme_percentage": "百分制",
  "applicant.scheme_other": "其他",
  "applicant.ielts": "雅思成绩 (IELTS)",
  "applicant.ielts_hint": "如有雅思成绩请填写，否则留空",
  "applicant.total": "总分",
  "applicant.reading": "阅读",
  "applicant.listening": "听力",
  "applicant.writing": "写作",
  "applicant.speaking": "口语",
  "applicant.toefl": "托福成绩 (TOEFL)",
  "applicant.toefl_hint": "如无雅思，填写托福成绩",
  "applicant.toefl_total": "总分",
  "applicant.toefl_placeholder": "如：92",
  "applicant.next_modules": "下一步：课程列表 →",
  "applicant.modules_title": "本科课程列表",
  "applicant.modules_hint": "添加你学过的主要课程（含必修课、专业课），系统将据此评估先修要求匹配度",
  "applicant.bulk_add": "粘贴批量添加课程",
  "applicant.course_name": "课程名称 *",
  "applicant.grade": "成绩 (如 A / 85)",
  "applicant.credits": "学分 (选填)",
  "applicant.add_course": "+ 添加课程",
  "applicant.confirm_title": "档案确认",
  "applicant.confirmed": "已添加 {count} 门课程",
  "applicant.submit": "提交评估 →",
  "applicant.submitting": "提交评估中...",
  "applicant.failed": "提交失败，请重试",

  // Results page
  "results.title": "评估结果",
  "results.total": "全部项目",
  "results.eligible": "符合条件",
  "results.borderline": "条件边缘",
  "results.not_eligible": "暂不符合",
  "results.filter.all": "全部",
  "results.filter.eligible": "符合条件",
  "results.filter.borderline": "边缘",
  "results.filter.not_eligible": "不符",
  "results.rerun": "重新评估中...",
  "results.rerun_btn": "♻ 重新评估",
  "results.loading": "加载评估结果中...",
  "results.no_results": "暂无评估结果",
  "results.go_create": "去创建申请档案 →",
  "results.no_applicant": "缺少申请者信息，请从申请入口重新进入。",
  "results.academic": "学术",
  "results.module_match": "模块匹配",
  "results.language_score": "语言",
  "results.gpa_title": "GPA / 学位等级",
  "results.language_title": "英语成绩",
  "results.prerequisite_title": "先修课程匹配",
  "results.compliance_title": "合规 / 签证提示",
  "results.summary_title": "综合评估",
  "results.view_official": "查看官方项目页面 →",

  // Risk tags
  "risk.atas": "ATAS",
  "risk.visa_deadline": "签证截止已过",
  "risk.non_visa_deadline": "申请截止已过",

  // Admin
  "admin.title": "管理后台",
  "admin.programmes": "项目列表",
  "admin.new_programme": "新建项目",
  "admin.verify": "待审核",
  "admin.example": "示例",
  "admin.import": "导入",
  "admin.export": "导出",
  "admin.refresh": "点击刷新",
  "admin.load_failed": "加载统计数据失败，请刷新页面。",
  "admin.statistics": "统计数据",
  "admin.programmes_count": "项目数量",
  "admin.universities_count": "大学数量",
  "admin.applicants_count": "申请者数量",
  "admin.workflow": "数据录入流程",

  // Timeline
  "timeline.title": "英国留学全程时间线",
  "timeline.subtitle": "从拿到 offer 到抵达英国 — 追踪 2026 年 9 月入学的每个关键节点",
  "timeline.jump_to_month": "跳转到月份",
  "timeline.phase": "阶段",
  "timeline.category": "类别",
  "timeline.all_phases": "全部阶段",
  "timeline.all": "全部",
  "timeline.events": "事件",
  "timeline.required": "必做",
  "timeline.done": "已完成",
  "timeline.current": "进行中",
  "timeline.upcoming": "待办",
  "timeline.no_events": "本月暂无此类别事件",
  "timeline.try_different": "试试切换月份或筛选条件",
  "timeline.overview_12": "12个月总览",
  "timeline.intensity_none": "无",
  "timeline.intensity_some": "少量",
  "timeline.intensity_busy": "繁忙",
  "timeline.intensity_current": "当前月",
  "timeline.disclaimer": "基于 UKVI 要求和 UCAS 指南，2026 年 9 月入学。日期为参考值，请以各院校官方截止日期为准。",

  // Common
  "common.submit": "提交",
  "common.cancel": "取消",
  "common.save": "保存",
  "common.delete": "删除",
  "common.edit": "编辑",
  "common.loading": "加载中...",
  "common.error": "错误",
  "common.success": "成功",
  "common.confirm": "确认",
  "common.required": "必填",
  "common.optional": "选填",
  "common.search": "搜索",
  "common.filter": "筛选",
  "common.no_data": "暂无数据",
};

export default dict;