const dict: Record<string, string> = {
  // Navigation
  "nav.back": "Back to Home",
  "nav.backTo": "Back",
  "nav.home": "Home",

  // Auth
  "auth.login": "Login",
  "auth.register": "Register",
  "auth.logout": "Logout",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.confirm_password": "Confirm Password",
  "auth.name": "Name",
  "auth.name_optional": "Name (Optional)",
  "auth.forgot_password": "Forgot password?",
  "auth.contact_admin": "Please contact your administrator to reset password",
  "auth.no_account": "Don't have an account?",
  "auth.have_account": "Already have an account?",
  "auth.login_now": "Login",
  "auth.register_now": "Register",
  "auth.create_account": "Create Account",
  "auth.login_success": "Login successful",
  "auth.register_success": "Registration successful",
  "auth.register_pending": "Registration successful! Please wait for Super Admin approval.",
  "auth.i_am": "I am a...",
  "auth.student": "Student",
  "auth.student_desc": "Apply for programmes",
  "auth.staff": "Staff",
  "auth.staff_desc": "Needs approval",
  "auth.staff_notice": "Staff accounts require approval from a Super Admin before you can login.",
  "auth.password_min": "Password must be at least 6 characters",
  "auth.passwords_not_match": "Passwords do not match",
  "auth.email_invalid": "Invalid email format",
  "auth.email_exists": "This email is already registered",
  "auth.email_password_wrong": "Incorrect email or password",
  "auth.pending_approval": "Your account is pending approval. Please contact your administrator.",
  "auth.rejected": "Your account has been rejected. Please contact your administrator.",
  "auth.suspended": "Your account has been suspended. Please contact your administrator.",
  "auth.login_failed": "Login failed, please try again",
  "auth.register_failed": "Registration failed, please try again",
  "auth.at_least_6_chars": "At least 6 characters",
  "auth.creating_account": "Creating account...",
  "auth.logging_in": "Logging in...",
  "auth.back_home": "Back to Home",

  // User Management (Admin)
  "admin.users.title": "User Management",
  "admin.users.subtitle": "Manage students and staff accounts",
  "admin.users.students": "Students",
  "admin.users.staff": "Staff",
  "admin.users.pending": "Pending Approval",
  "admin.users.total": "Total Users",
  "admin.users.all": "All Users",
  "admin.users.pending_only": "Pending",
  "admin.users.search_placeholder": "Search by email or name...",
  "admin.users.user": "User",
  "admin.users.role": "Role",
  "admin.users.status": "Status",
  "admin.users.registered": "Registered",
  "admin.users.actions": "Actions",
  "admin.users.manage": "Manage",
  "admin.users.no_users": "No users found",
  "admin.users.no_pending": "No pending approvals",
  "admin.users.user_details": "User Details",
  "admin.users.last_login": "Last Login",
  "admin.users.approve": "Approve",
  "admin.users.reject": "Reject",
  "admin.users.suspend": "Suspend",
  "admin.users.activate": "Activate",
  "admin.users.reset_password": "Reset Password",
  "admin.users.new_password": "New Password Generated",
  "admin.users.share_password": "Please share this password with the user securely.",
  "admin.users.cannot_modify_admin": "Cannot modify Super Admin account",
  "admin.users.processing": "Processing...",

  // Staff Dashboard
  "staff.dashboard.title": "Staff Dashboard",
  "staff.dashboard.welcome": "Welcome, Staff Member!",
  "staff.dashboard.desc": "Manage programmes, review applications, and help students find their perfect match.",
  "staff.dashboard.programmes": "Programmes",
  "staff.dashboard.programmes_desc": "View, edit, and add UK engineering programmes",
  "staff.dashboard.verify": "Data Review",
  "staff.dashboard.verify_desc": "Verify parsed data and ensure accuracy",
  "staff.dashboard.add_programme": "Add Programme",
  "staff.dashboard.add_programme_desc": "Manually add new programmes and requirements",
  "staff.dashboard.responsibilities": "Your Responsibilities",
  "staff.dashboard.resp_1": "Maintain accurate programme information from official university websites",
  "staff.dashboard.resp_2": "Verify AI-parsed data before it goes live",
  "staff.dashboard.resp_3": "Monitor student applications and provide support",
  "staff.dashboard.resp_4": "Update timeline events and deadlines as needed",

  // Homepage
  "home.title": "EngiMatch",
  "home.subtitle": "UK Engineering Master's Programme Matching",
  "home.description": "Accurately evaluate UK university fit for engineering undergraduates",
  "home.ai_resume": "AI Resume Optimizer",
  "home.ai_resume_desc": "Check if your resume is suitable for UK engineering master's applications, with paragraph-by-paragraph improvement suggestions",
  "home.create_profile": "Create Application Profile",
  "home.create_profile_desc": "Enter your academic records and background information",
  "home.timeline": "Application Timeline",
  "home.timeline_desc": "Track IELTS, visa, flights, accommodation and more",
  "home.admin": "Admin Dashboard",
  "home.admin_desc": "Manage programmes and evaluation rules",
  "home.login": "Login",
  "home.register": "Register",
  "home.logout": "Logout",
  "home.go_dashboard": "Go to Dashboard",

  // AI Resume
  "ai.title": "AI Resume Optimizer",
  "ai.subtitle": "AI-Powered · For UK Taught Master's Applications Only",
  "ai.description": "Check if your resume is suitable for UK engineering master's applications, analyze section by section, and provide professional optimization suggestions.",
  "ai.step.usecase": "Select Scenario",
  "ai.step.upload": "Upload Resume",
  "ai.step.review": "Confirm Parsing",
  "ai.step.diagnose": "View Diagnostics",
  "ai.step.optimize": "Section Optimization",
  "ai.step.final": "Final Version",
  "ai.application_type": "Application Type",
  "ai.uk_master": "UK Taught Master's",
  "ai.uk_master_desc": "MSc / MEng · Main Track",
  "ai.research_master": "Research Master's (MRes)",
  "ai.research_master_desc": "Not yet supported",
  "ai.major_direction": "Discipline (Required)",
  "ai.current_stage": "Current Stage",
  "ai.stage.no_resume": "No resume yet, want to learn first",
  "ai.stage.have_resume": "Already have a resume, want to optimize",
  "ai.stage.apply_ready": "Ready to apply, want to check eligibility",
  "ai.start": "Start Upload →",

  // Upload page
  "upload.title": "Upload Resume",
  "upload.paste_mode": "Paste Resume Text",
  "upload.upload_mode": "Upload File (PDF/Word)",
  "upload.paste_content": "Paste Resume Content",
  "upload.paste_hint": "Paste English or mixed Chinese-English resumes",
  "upload.paste_clipboard": "📋 Paste from Clipboard",
  "upload.upload_file": "Upload Resume File",
  "upload.supported": "Supports PDF, Word (.doc/.docx), Plain text (.txt)",
  "upload.select_file": "Select File",
  "upload.note": "Note: PDF/Word formats require server-side parsing libraries. If extraction fails, please use paste mode instead.",
  "upload.characters": "{count} characters entered",
  "upload.too_short": "(Content may be insufficient)",
  "upload.continue": "Parse Resume →",
  "upload.need_more": "{count} more characters needed",
  "upload.extracting": "Extracting text...",
  "upload.direction": "Direction: UK Taught Master's",
  "upload.direction_edit": "Edit →",

  // Review page
  "review.title": "Resume Structure Parsing Results",
  "review.add_section": "+ Add Section",
  "review.description": "The system has split your resume into {count} sections. Please confirm if the categorization is correct.",
  "review.hint": "System Hint",
  "review.confirm": "Confirm and Start Diagnostics →",
  "review.splitting_method": "Splitting Method",
  "review.rule_based": "Rule-based",
  "review.ai_smart_split": "AI Smart Split",
  "review.splitting": "Splitting...",
  "review.education_missing": "Education section not detected, please add manually",
  "review.project_missing": "Project or research experience not detected, please confirm if included",
  "review.skill_missing": "Skills section not detected, recommend adding programming languages and tools",
  "review.parse_failed": "Could not parse content, please paste resume text and restart",
  "review.resume_direction": "Resume will be evaluated and optimized for this direction",

  // Diagnose page
  "diagnose.title": "Diagnostic Results",
  "diagnose.structure": "Structure Clarity",
  "diagnose.completeness": "Content Completeness",
  "diagnose.target_fit": "Application Fit",
  "diagnose.english_quality": "English Writing Quality",
  "diagnose.continue": "Start Section Optimization →",
  "diagnose.diagnosis_complete": "Diagnosis Complete",
  "diagnose.diagnosis_desc": "Analyze your resume from four dimensions: structure, content, application fit, and English writing quality",
  "diagnose.issues_found": "Issues Found",
  "diagnose.high_priority": "High Priority",
  "diagnose.med_priority": "Medium Priority",
  "diagnose.low_priority": "Low Priority",
  "diagnose.structure_good": "Resume basic structure is good",
  "diagnose.structure_good_desc": "No obvious issues detected, recommend proceeding to optimization",
  "diagnose.issue_description": "Issue Description",
  "diagnose.suggestion": "Optimization Suggestion",
  "diagnose.deep_analysis": "AI Deep Analysis in Progress...",
  "diagnose.deep_analysis_desc": "Providing targeted evaluation based on your resume content",
  "diagnose.deep_report": "AI Deep Analysis Report",
  "diagnose.overall_review": "Overall Review",
  "diagnose.ai_unavailable": "AI diagnostics temporarily unavailable",
  "diagnose.modify_parsing": "Modify Parsing",
  "diagnose.start_optimize": "Start Optimization →",
  "diagnose.recommendations": "Recommendations",

  // Optimize page
  "optimize.title": "Optimize Resume",
  "optimize.select_section": "Select a section to start optimization",
  "optimize.optimizing": "Optimizing...",
  "optimize.original": "Original",
  "optimize.optimized": "Optimized",
  "optimize.apply_all": "Apply All Optimizations",
  "optimize.skip": "Skip",

  // Final page
  "final.title": "Final Version",
  "final.download": "Download Resume",
  "final.copy": "Copy Full Text",
  "final.copied": "Copied",
  "final.start_over": "Start Over",
  "final.success": "Resume optimization complete!",

  // Common section types
  "section.education": "Education",
  "section.project": "Projects",
  "section.internship": "Internship",
  "section.research": "Research",
  "section.competition": "Competitions",
  "section.skill": "Skills & Tools",
  "section.award": "Awards",
  "section.summary": "Summary",
  "section.other": "Other",
  "section.new": "New Section",
  "section.title_placeholder": "Section title",
  "section.content_placeholder": "Edit content here...",
  "section.personal_info": "Personal Info",

  // Applicant page
  "applicant.title": "Create Application Profile",
  "applicant.subtitle": "Enter your academic background to get UK engineering master's programme matching results",
  "applicant.step1": "Personal Info",
  "applicant.step2": "Academic Scores",
  "applicant.step3": "Course List",
  "applicant.personal_info": "Personal Information",
  "applicant.auto_fill": "Paste Auto-fill",
  "applicant.hide_example": "Hide Example",
  "applicant.name": "Full Name *",
  "applicant.name_placeholder": "Your real name",
  "applicant.email": "Email *",
  "applicant.email_placeholder": "For receiving results",
  "applicant.nationality": "Nationality",
  "applicant.nationality_placeholder": "e.g., China",
  "applicant.university": "Undergraduate University *",
  "applicant.university_placeholder": "e.g., Tongji University",
  "applicant.major": "Undergraduate Major *",
  "applicant.major_placeholder": "e.g., Mechanical Engineering",
  "applicant.graduation_year": "Expected Graduation Year",
  "applicant.target_direction": "Target Application Direction",
  "applicant.target_hint": "Multiple selection allowed, helps us filter most relevant programmes",
  "applicant.next_step": "Next: Academic Scores →",
  "applicant.prev_step": "← Previous",
  "applicant.gpa": "GPA Score *",
  "applicant.gpa_value": "GPA Value",
  "applicant.gpa_value_placeholder": "e.g., 3.5",
  "applicant.gpa_scale": "Scale",
  "applicant.gpa_scale_placeholder": "e.g., 4.0",
  "applicant.grading_scheme": "Grading Scheme",
  "applicant.scheme_4": "4.0 Scale",
  "applicant.scheme_5": "5.0 Scale",
  "applicant.scheme_percentage": "Percentage",
  "applicant.scheme_other": "Other",
  "applicant.ielts": "IELTS Score",
  "applicant.ielts_hint": "Please fill in if you have IELTS score, otherwise leave blank",
  "applicant.total": "Overall",
  "applicant.reading": "Reading",
  "applicant.listening": "Listening",
  "applicant.writing": "Writing",
  "applicant.speaking": "Speaking",
  "applicant.toefl": "TOEFL Score",
  "applicant.toefl_hint": "Fill in TOEFL score if no IELTS",
  "applicant.toefl_total": "Total Score",
  "applicant.toefl_placeholder": "e.g., 92",
  "applicant.next_modules": "Next: Course List →",
  "applicant.modules_title": "Undergraduate Course List",
  "applicant.modules_hint": "Add your main courses (required courses, major courses). The system will evaluate prerequisite match based on this.",
  "applicant.bulk_add": "Paste Bulk Add Courses",
  "applicant.course_name": "Course Name *",
  "applicant.grade": "Grade (e.g., A / 85)",
  "applicant.credits": "Credits (Optional)",
  "applicant.add_course": "+ Add Course",
  "applicant.confirm_title": "Profile Confirmation",
  "applicant.confirmed": "{count} courses added",
  "applicant.submit": "Submit for Evaluation →",
  "applicant.submitting": "Submitting...",
  "applicant.failed": "Submission failed, please try again",

  // Results page
  "results.title": "Evaluation Results",
  "results.total": "All Programmes",
  "results.eligible": "Eligible",
  "results.borderline": "Borderline",
  "results.not_eligible": "Not Eligible",
  "results.filter.all": "All",
  "results.filter.eligible": "Eligible",
  "results.filter.borderline": "Borderline",
  "results.filter.not_eligible": "Ineligible",
  "results.rerun": "Re-evaluating...",
  "results.rerun_btn": "♻ Re-evaluate",
  "results.loading": "Loading evaluation results...",
  "results.no_results": "No evaluation results yet",
  "results.go_create": "Go to Create Application Profile →",
  "results.no_applicant": "Missing applicant information. Please enter from the application portal.",
  "results.academic": "Academic",
  "results.module_match": "Module Match",
  "results.language_score": "Language",
  "results.gpa_title": "GPA / Degree Classification",
  "results.language_title": "English Score",
  "results.prerequisite_title": "Prerequisite Courses Match",
  "results.compliance_title": "Compliance / Visa Notice",
  "results.summary_title": "Overall Assessment",
  "results.view_official": "View Official Programme Page →",

  // Risk tags
  "risk.atas": "ATAS",
  "risk.visa_deadline": "Visa Deadline Passed",
  "risk.non_visa_deadline": "App Deadline Passed",

  // Admin
  "admin.title": "Admin Dashboard",
  "admin.programmes": "Programmes",
  "admin.new_programme": "New Programme",
  "admin.verify": "Pending Review",
  "admin.example": "Example",
  "admin.import": "Import",
  "admin.export": "Export",
  "admin.refresh": "Click to refresh",
  "admin.load_failed": "Failed to load statistics. Please refresh the page.",
  "admin.statistics": "Statistics",
  "admin.programmes_count": "Programmes",
  "admin.universities_count": "Universities",
  "admin.applicants_count": "Applicants",
  "admin.workflow": "Data Entry Workflow",

  // Timeline
  "timeline.title": "UK Study Journey Timeline",
  "timeline.subtitle": "From offer acceptance to arrival in the UK — track every key milestone for your September 2026 intake",
  "timeline.jump_to_month": "Jump to month",
  "timeline.phase": "Phase",
  "timeline.category": "Category",
  "timeline.all_phases": "All Phases",
  "timeline.all": "All",
  "timeline.events": "events",
  "timeline.required": "required",
  "timeline.done": "Done",
  "timeline.current": "Current",
  "timeline.upcoming": "Upcoming",
  "timeline.no_events": "No events for this month",
  "timeline.try_different": "Try a different month or filter",
  "timeline.overview_12": "12-Month Overview",
  "timeline.intensity_none": "None",
  "timeline.intensity_some": "Some",
  "timeline.intensity_busy": "Busy",
  "timeline.intensity_current": "Current",
  "timeline.disclaimer": "Based on UKVI requirements and UCAS guidelines for September 2026 intake. Dates are approximate — always check your university's official deadlines.",

  // Common
  "common.submit": "Submit",
  "common.cancel": "Cancel",
  "common.save": "Save",
  "common.delete": "Delete",
  "common.edit": "Edit",
  "common.loading": "Loading...",
  "common.error": "Error",
  "common.success": "Success",
  "common.confirm": "Confirm",
  "common.required": "Required",
  "common.optional": "Optional",
  "common.search": "Search",
  "common.filter": "Filter",
  "common.no_data": "No data",
};

export default dict;